name: Spring Boot CI

on:
  push:

jobs:
  build-and-test:
    name: Build Version
    runs-on: ubuntu-latest
    container: maven:3.8.7-amazoncorretto-17
    steps:
      - uses: actions/checkout@v2
      - run: mvn --version
      - run: ls -l
      - run: mvn clean install
      - name: Upload jar file
        uses: actions/upload-artifact@v3
        with:
          name: demo-1.0.0.jar
          path: ./target/github-actions-demo-0.0.1-SNAPSHOT.jar
