name: Spring Boot CI

on:
  push:

jobs:
  build-and-test:
    name: Build Version
    runs-on: ubuntu-latest
    container: maven:3.8.7-amazoncorretto-17
    steps:
      - uses: actions/checkout@v2
      - run: mvn --version
      - run: ls -l
      - run: mvn install
